src/main/java/lt/akademija/perlaikymas/entities/Coupon.java
package lt.akademija.perlaikymas.entities;

import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotBlank;

@Entity
public class Coupon {
	@Id
	@GeneratedValue
	private Long id;
	@Temporal(TemporalType.DATE)
	private Date date;
	@NotNull
	@NotBlank
	private String seller;
	@Size(min=1)
	private String buyer;
	
	@OneToMany(mappedBy="coupon", orphanRemoval=true, fetch=FetchType.EAGER, cascade=CascadeType.ALL )
	private List<Item> items;
	
	public Coupon(){}
	
	public Coupon(Date date, String buyer, String seller) {
		super();
		this.date = date;
		this.buyer = buyer;
		this.seller = seller;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getSeller() {
		return buyer;
	}

	public void setSeller(String buyer) {
		this.buyer = buyer;
	}

	public String getBuyer() {
		return seller;
	}

	public void setBuyer(String seller) {
		this.seller = seller;
	}

	public List<Item> getItems() {
		return items;
	}

	public void setItems(List<Item> items) {
		this.items = items;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	public String convertDateToString(Date date){
		Format formatter = new SimpleDateFormat("yyyy-MM-dd");
		String s = formatter.format(date);
		return s;
	}
}

src/main/java/lt/akademija/perlaikymas/entities/Item.java
package lt.akademija.perlaikymas.entities;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotBlank;

@Entity
public class Item {
	@Id
	@GeneratedValue
	private Long id;
	@NotNull
	@NotBlank
	private String name;
	@Min(0)
	private Integer amount;
	private String unit;
	@NotNull
	private Integer price;
	
//	@JoinColumn(name="coupon_id")
	@ManyToOne(optional = true)
	private Coupon coupon;
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public Integer getAmount() {
		return amount;
	}
	public void setAmount(Integer amount) {
		this.amount = amount;
	}
	public String getUnit() {
		return unit;
	}
	public void setUnit(String unit) {
		this.unit = unit;
	}
	public Integer getPrice() {
		return price;
	}
	public void setPrice(Integer price) {
		this.price = price;
	}
	public Coupon getCoupon() {
		return coupon;
	}
	public void setCoupon(Coupon coupon) {
		this.coupon = coupon;
	}
	public Integer getTotal(){
		if (amount == null || price == null){
			return 0;
		}
		return (Integer)(amount*price);
	}
	
}

src/main/java/lt/akademija/perlaikymas/models/CouponModel.java
package lt.akademija.perlaikymas.models;

import javax.validation.Valid;

import lt.akademija.perlaikymas.entities.Coupon;
import lt.akademija.perlaikymas.entities.Item;

public class CouponModel {
	@Valid
	private Coupon currentCoupon;
	private Double total;

	public Coupon getCurrentCoupon() {
		return currentCoupon;
	}

	public void setCurrentCoupon(Coupon currentCoupon) {
		this.currentCoupon = currentCoupon;
	}
	
	public Double getCalculatedSum(){
		Double sum = 0.0;
		for (Item item: getCurrentCoupon().getItems()){
			sum = sum + item.getAmount()*item.getPrice();
		}
		return sum;
	}

	public Double getTotal() {
		return total;
	}
}

src/main/java/lt/akademija/perlaikymas/models/ItemModel.java
package lt.akademija.perlaikymas.models;

import lt.akademija.perlaikymas.entities.Item;

public class ItemModel {
	
	private Item currentItem;

	public Item getCurrentItem() {
		return currentItem;
	}

	public void setCurrentItem(Item currentItem) {
		this.currentItem = currentItem;
	}
}

src/main/java/lt/akademija/perlaikymas/controllers/BackingBean.java
package lt.akademija.perlaikymas.controllers;

import org.primefaces.context.RequestContext;

public class BackingBean {
	CouponController couponController;
	ItemController itemController;
	private boolean priceTooHigh;
	
	public boolean getShowNotificationBar(){
		if (couponController.getCouponList().size()<2){
			return true;
		}
		return false;
	}
	
	public boolean getShowNotificationBarForItems(){
		if (couponController.getCouponModel().getCurrentCoupon().getItems().size() < 1){
			return true;
		}
		return false;
	}
	
	public void changeColorOnPrice(){
		RequestContext rc = RequestContext.getCurrentInstance();
		Integer totalPrice = itemController.getItemModel().getCurrentItem().getTotal();
		if ( totalPrice < 2){
			rc.execute("document.getElementById('forma:out').setAttribute('class', 'redcolor')");
			priceTooHigh = false;
		}
		if (totalPrice > 2){
			rc.execute("document.getElementById('forma:out').setAttribute('class', 'greencolor')");
			priceTooHigh = false;
		}
		if (totalPrice >1000){
			priceTooHigh = true;
			rc.update("forma:mess");
		}
		
	}
			
	public CouponController getCouponController() {
		return couponController;
	}
	public void setCouponController(CouponController couponController) {
		this.couponController = couponController;
	}
	public ItemController getItemController() {
		return itemController;
	}
	public void setItemController(ItemController itemController) {
		this.itemController = itemController;
	}

	public boolean isPriceTooHigh() {
		return priceTooHigh;
	}
	
}

src/main/java/lt/akademija/perlaikymas/controllers/CouponController.java
package lt.akademija.perlaikymas.controllers;

import java.util.List;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import lt.akademija.perlaikymas.dao.CouponDao;
import lt.akademija.perlaikymas.entities.Coupon;
import lt.akademija.perlaikymas.entities.Item;
import lt.akademija.perlaikymas.models.CouponModel;

public class CouponController {
	
	private static final Logger logger = LogManager.getLogger(CouponController.class.getName());
	
	private CouponModel couponModel;
	private CouponDao couponDao;
	

	public List<Coupon> getCouponList() {
		return couponDao.findAll();
	}
	
	public String create(){
		couponModel.setCurrentCoupon(new Coupon());
		return "create-coupon";
	}
	
	public String update(Coupon coupon){
		couponModel.setCurrentCoupon(coupon);
		logger.info("Coupon updated");
		return "update-coupon";
	}
	
	public String cancel(){
		couponModel.setCurrentCoupon(null);
		return "coupon-list";
	}
	
	public String save(){
		couponDao.save(couponModel.getCurrentCoupon());
		if(couponModel.getCurrentCoupon().getId() == null){
			logger.info("New coupon created");
		}
		else logger.info("Coupon updated");
		return "coupon-list";
	}
	
	public Coupon findCouponById(Long id){
		return couponDao.findById(id);
	}
	
	public void delete(Coupon coupon){
		logger.info("Coupon was deleted");
		couponDao.delete(coupon);
	}

	public String overview(Coupon coupon){
		couponModel.setCurrentCoupon(coupon);
		return "coupon-overview";
	}
	
	public CouponModel getCouponModel() {
		return couponModel;
	}

	public void setCouponModel(CouponModel couponModel) {
		this.couponModel = couponModel;
	}

	public CouponDao getCouponDao() {
		return couponDao;
	}

	public void setCouponDao(CouponDao couponDao) {
		this.couponDao = couponDao;
	}

	public List<Item> getAllItems(){
		return couponDao.findAllItems();
	}
}

src/main/java/lt/akademija/perlaikymas/controllers/ItemController.java
package lt.akademija.perlaikymas.controllers;


import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import lt.akademija.perlaikymas.entities.Coupon;
import lt.akademija.perlaikymas.entities.Item;
import lt.akademija.perlaikymas.models.ItemModel;

public class ItemController {

	private static final Logger logger = LogManager.getLogger(ItemController.class.getName());
	
	private CouponController couponController;
	private ItemModel itemModel;
	
	
	public String create(){
		itemModel.setCurrentItem(new Item());
		return "update-item";
	}
	
	public String update(Item item){
		logger.info("Item updated");
		itemModel.setCurrentItem(item);
		return "update-item";
	}
	
	public String delete(Item item){
		Coupon coupon = couponController.getCouponModel().getCurrentCoupon();
		Long id = coupon.getId();
		coupon.getItems().remove(item);
		couponController.save();
		couponController.getCouponModel().setCurrentCoupon(couponController.findCouponById(id));
		logger.info("Item was deleted");
		return "update-coupon";
		
	}
	
	public String save(){
		Coupon coupon = couponController.getCouponModel().getCurrentCoupon();
		Item item = itemModel.getCurrentItem();
		Long id = coupon.getId();
		if (!coupon.getItems().contains(item)){
			item.setCoupon(coupon);
			coupon.getItems().add(item);
		}
		couponController.save();
		couponController.getCouponModel().setCurrentCoupon(couponController.findCouponById(id));
		if(itemModel.getCurrentItem().getId() == null){
			logger.info("New item created");
		}
		else logger.info("Item was updated");
		return "update-coupon";
	}
	
	public String cancel(){
		itemModel.setCurrentItem(null);
		Coupon coupon = couponController.getCouponModel().getCurrentCoupon();
		Long id = coupon.getId();
		couponController.getCouponModel().setCurrentCoupon(couponController.findCouponById(id));
		return "update-coupon";
	}

	public CouponController getCouponController() {
		return couponController;
	}

	public void setCouponController(CouponController couponController) {
		this.couponController = couponController;
	}

	public ItemModel getItemModel() {
		return itemModel;
	}

	public void setItemModel(ItemModel itemModel) {
		this.itemModel = itemModel;
	}

}

src/main/webapp/add_coupon.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      template="template.xhtml">

	<ui:define name="content">
 
 		<h:form>
 			<p:messages id="messages" showDetail="true" autoUpdate="true" closable="true" />
 	   		<p:panel id="basic" header="Add new coupon" style="margin-bottom:20px">
				<h:panelGrid id="grid" columns="3" cellpadding="5">
     			
     				<p:outputLabel for="date">Date: </p:outputLabel>
     				<p:inputText id="date" value="#{couponModel.currentCoupon.date}" required="true" converterMessage="Use format YYYY-MM-DD">
     					<f:convertDateTime pattern="yyyy-M-d" />
     				</p:inputText>
     				<p:message for="date" />
     			
     				<p:outputLabel for="seller">Seller: </p:outputLabel>
     				<p:inputText id="seller" value="#{couponModel.currentCoupon.seller}" required="true" requiredMessage="Please enter some name" validatorMessage="This field cant not be empty">
     					<f:validateBean/>
     				</p:inputText>
     				<p:message for="seller" />
     			
     				<p:outputLabel for="buyer">Buyer: </p:outputLabel>
     				<p:inputText id="buyer" value="#{couponModel.currentCoupon.buyer}" required="true" >
     					<f:validateBean/>
     				</p:inputText>
     				<p:message for="buyer" />
     	
     			</h:panelGrid>
     		</p:panel>
     		<p:commandButton value="Save" action="#{couponController.save()}" update="@form"/>
     		<p:commandButton value="Cancel" action="#{couponController.cancel()}" immediate="true"/>
  		</h:form>
  
	</ui:define>

	<ui:define name="page_title">
		Add new coupon
	</ui:define>

</ui:composition>

src/main/webapp/coupon.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      template="template.xhtml">

	<ui:define name="content">
 		<h:form>
      		<p:dataTable class="table" value="#{couponModel.currentCoupon}" var="coupon">
       	 		<f:facet name="header">
        			Coupon details
    			</f:facet>
      			<p:column headerText="Number">
      				<h:outputText value="#{coupon.id}"/>
      			</p:column>
      			<p:column headerText="Date">
      				<h:outputText value="#{coupon.date}"/>
      			</p:column>
      			<p:column headerText="Seller">
      				<h:outputText value="#{coupon.seller}"/>
      			</p:column>
      			<p:column headerText="Recipient">
      				<h:outputText value="#{coupon.buyer}"/>
      			</p:column>
 
      		</p:dataTable>
      	</h:form>
  		
  		<h:form>
 			<p:dataTable class="table" value="#{couponModel.currentCoupon.items}" var="item">
 		    	<f:facet name="header">
        			Coupon items
    			</f:facet>
      			<p:column headerText="Name">
      				<h:outputText value="#{item.name}"/>
      			</p:column>
      	    	<p:column headerText="Amount">
      				<h:outputText value="#{item.amount}"/>
      			</p:column>
      	    	<p:column headerText="Unit">
      				<h:outputText value="#{item.unit}"/>
      			</p:column>
      			<p:column headerText="Item price">
      				<h:outputText value="#{item.price}"/>
      			</p:column>
      			<p:column headerText="Total price">
      				<h:outputText value="#{item.total}"/>
      			</p:column>
       			<p:columnGroup type="footer">
            		<p:row>
                		<p:column colspan="4" style="text-align:right" footerText="Totals:" />
                		<p:column footerText="#{couponModel.calculatedSum}" />
            		</p:row>
        		</p:columnGroup>
  			</p:dataTable>
		
  		</h:form>
	</ui:define>

	<ui:define name="page_title">
		Coupon details
	</ui:define>
</ui:composition>

src/main/webapp/coupons.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      template="template.xhtml">

	<ui:define name="content">
  		<h:form>
      		<p:dataTable class="table" value="#{couponController.couponList}" var="coupon">
        		<f:facet name="header">
       	 			Coupons
    			</f:facet>
      			<p:column headerText="Number">
      				<h:outputText value="#{coupon.id}"/>
      			</p:column>
      			<p:column headerText="Date">
      				<h:outputText value="#{coupon.date}"/>
      			</p:column>
      			<p:column headerText="Seller">
      				<h:outputText value="#{coupon.seller}"/>
      			</p:column>
      			<p:column headerText="Buyer">
      				<h:outputText value="#{coupon.buyer}"/>
      			</p:column>
      	
      			<p:column headerText="Operations">
      	   	
      	   			<p:commandLink action="#{couponController.overview(coupon)}" value="Overview "></p:commandLink>
      	   	
      				<p:commandLink action="#{couponController.update(coupon)}" value="Update "></p:commandLink>
      		
      				<p:commandLink actionListener="#{couponController.delete(coupon)}" update="@form" value="Delete " immidiate="true">
      					<p:confirm header="Confirmation" message="Are you sure?" icon="ui-icon-alert"></p:confirm>
      				</p:commandLink>
      		
      			</p:column>
      		</p:dataTable>
      
      		<p:commandButton action="#{couponController.create}" value="Create new coupon"/>
      
      		<p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
      	  		<p:commandButton value="Yes" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
        		<p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
      		</p:confirmDialog>
  		</h:form>
  
  		<form>
  			<p:notificationBar position="bottom" effect="slide" styleClass="top" widgetVar="bar" rendered="#{backingBean.showNotificationBar}" autoDisplay="true">
    			<h:outputText value="Add more coupons!" style="font-size:36px;" />
			</p:notificationBar>
  		</form>
  
	</ui:define>

	<ui:define name="page_title">
		Coupon list
	</ui:define>
</ui:composition>

src/main/webapp/edit_coupon.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      template="template.xhtml">

	<ui:define name="content">
 
		<h:form>
	  		<p:messages id="messages" showDetail="true" autoUpdate="true" closable="true" />
      		<p:dataTable class="table" value="#{couponModel.currentCoupon}" var="coupon">
        		<f:facet name="header">
        			Coupon details
    			</f:facet>
      			<p:column headerText="Number">
      				<h:outputText value="#{coupon.id}"/>
      			</p:column>
      			<p:column headerText="Date">
      				<p:inputText value="#{coupon.date}" converterMessage="Use format YYYY-MM-DD">
      					<f:convertDateTime pattern="yyyy-MM-dd" />
      				</p:inputText>
      			</p:column>
      			<p:column headerText="Seller">
      				<p:inputText value="#{coupon.seller}"/>
      			</p:column>
      			<p:column headerText="Buyer">
      				<p:inputText value="#{coupon.buyer}"/>
      			</p:column>
      		</p:dataTable>
      		<p:commandButton value="Save coupon details" action="#{couponController.save()}" update="@form"/>
     		<p:commandButton value="Cancel" action="#{couponController.cancel()}" immediate="true"/>
      		<h:outputText value="EAN-13" />
   			 <p:barcode value="#{couponModel.currentCoupon.convertDateToString(couponModel.currentCoupon.date)}" type="ean13"/>
      	</h:form>
      
	  	<h:form>
 			<p:dataTable class="table" value="#{couponModel.currentCoupon.items}" var="item">
 		    	<f:facet name="header">
        			Coupon items
    			</f:facet>
      			<p:column headerText="Name">
      				<h:outputText value="#{item.name}"/>
      			</p:column>
      	    	<p:column headerText="Amount">
      				<p:inputText value="#{item.amount}"/>
      			</p:column>
      	    	<p:column headerText="Unit">
      				<h:outputText value="#{item.unit}"/>
      			</p:column>
      			<p:column headerText="Item price">
      				<p:inputText value="#{item.price}"/>
      			</p:column>
      	
      			<p:column headerText="Operations">
      				<p:commandLink action="#{itemController.update(item)}" value="Update ">
      				</p:commandLink>
      				<p:commandLink action="#{itemController.delete(item)}" update="@form" value="Delete " immidiate="true">
      					<p:confirm header="Confirmation" message="Are you sure?" icon="ui-icon-alert"></p:confirm>
      				</p:commandLink>
      			</p:column>
      		</p:dataTable>
      		<p:commandButton action="#{itemController.create}" value="Add new item"/>
      		<p:commandButton value="Save coupon details" action="#{couponController.save()}" update="@form"/>
      	
      		<p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
      	  			<p:commandButton value="Yes" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
        			<p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
      		</p:confirmDialog>
      	</h:form>
  		<br/>
  		<br/>
  		<br/>
  		<br/>
  		<br/>
  		<br/>

  		<form>
  			<p:notificationBar position="bottom" effect="slide" styleClass="top" widgetVar="bar" rendered="#{backingBean.showNotificationBarForItems}" autoDisplay="true">
    			<h:outputText value="You must add at least one item to the coupon!" style="font-size:36px;" />
			</p:notificationBar>
  		</form>

	</ui:define>

	<ui:define name="page_title">
		Edit coupon
	</ui:define>

</ui:composition>

src/main/webapp/edit_item.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      template="template.xhtml">
      

	<ui:define name="content">
  		<h:form id="forma">
     		<p:panel id="basic" header="Add/Update item" style="margin-bottom:20px">
				<h:panelGrid id="grid" columns="3" cellpadding="5">
     				<p:outputLabel for="name">Name: </p:outputLabel>
     				<p:inputText id="name" value="#{itemModel.currentItem.name}">
     					<f:validateBean/>
     				</p:inputText>
     				<p:message for="name" />
     			
     				<p:outputLabel for="amount">Amount: </p:outputLabel>
     				<p:inputText id="amount" value="#{itemModel.currentItem.amount}">
     					<f:validateBean/>
     					<p:ajax event="keyup" update="amountField"/>
     					<p:ajax event="keyup" listener="#{backingBean.changeColorOnPrice}" update="out, amountField"></p:ajax>
     				</p:inputText>
     				<p:message for="amount" />
     			
     				<p:outputLabel for="unit">Unit: </p:outputLabel>
     				<p:inputText id="unit" value="#{itemModel.currentItem.unit}"/>
     				<p:message for="unit" />
     			
     				<p:outputLabel for="price">Price: </p:outputLabel>
     				<p:inputText id="price" value="#{itemModel.currentItem.price}">
     					<f:validateBean/>
     					<p:ajax event="keyup" update="priceField"/>
     					<p:ajax event="keyup" listener="#{backingBean.changeColorOnPrice}" update="out"/>
     				</p:inputText>
     				<p:message for="price" />
     			</h:panelGrid>
     		
     			<h:outputText id="out" value="Price: #{itemModel.currentItem.total}" ></h:outputText>
     			<p:panel id="mess" widgetVar="mess">
     		     	<h:outputText value="Price is higher than 1000" rendered="#{backingBean.priceTooHigh}" styleClass="yellowcolor"></h:outputText>
     			</p:panel>
     			<h:panelGrid columns="2" cellpadding="5">
     				<h:outputText value="Amount: "></h:outputText>
     				<h:outputText id="amountField" value="#{itemModel.currentItem.amount}"></h:outputText>
     				<h:outputText value="Price: "></h:outputText>
     				<h:outputText id="priceField" value="#{itemModel.currentItem.price}"></h:outputText>
     			</h:panelGrid>
     		</p:panel>
     		<p:commandButton value="Save" action="#{itemController.save}" update="@form"/>
     		<p:commandButton value="Cancel" action="#{itemController.cancel}" immediate="true"/>
  		</h:form>
	</ui:define>

	<ui:define name="page_title">
		Add/edit item
	</ui:define>
</ui:composition>

src/main/webapp/items.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      template="template.xhtml">

	<ui:define name="content">
  		<h:form>
      		<p:dataTable class="table" value="#{couponController.allItems}" var="item">
        		<f:facet name="header">
       	 			Coupon
    			</f:facet>
      			<p:column headerText="Number">
      				<h:outputText value="#{item.id}"/>
      			</p:column>
      			<p:column headerText="Name">
      				<h:outputText value="#{item.name}"/>
      			</p:column>
      		</p:dataTable>
      	</h:form>
	</ui:define>

	<ui:define name="page_title">
		Item list
	</ui:define>
</ui:composition>

src/main/webapp/menu.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
  

	<ui:composition>
		<h:form>
			<p:tabMenu>
				<p:menuitem value="Back to coupon list" outcome="coupon-list"
					icon="ui-icon-star">
				</p:menuitem>
			</p:tabMenu>
		</h:form>
	</ui:composition>
 	
</html>

src/main/webapp/template.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
      
	<h:head>
  		<title>MyApp 5.0 
  			<ui:insert name="page_title"></ui:insert>
  		</title>
  		<h:outputStylesheet library="style" name="dmitrij-perlaikymas.css"></h:outputStylesheet>
	</h:head>

	<h:body>

		<div class="menu">
			<h:form>
				<p:tabMenu>
					<p:menuitem value="Back to coupon list" outcome="coupon-list" icon="ui-icon-star"></p:menuitem>
					<p:menuitem value="Items" outcome="items" icon="ui-icon-star"></p:menuitem>
				</p:tabMenu>
			</h:form>
		</div>
	
		<div class="context">
			<ui:insert name="content"/>
		</div>
  
	</h:body>
</html>